name: VitalApp CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Cambia si tu rama se llama diferente
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        pytest

    - name: Analizar calidad del código (flake8)
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Construir imagen Docker
      run: |
        docker build -t vitalapp .

    # Puedes agregar despliegue a Railway o servidor si quieres aquí
    # - name: Deploy a staging...
